[meta]
version = "0.1"

[appraisals.dimension_to_statement]
"relevance.general" = "This situation matters to me."
"relevance.urgency" = "I need to do something about this situation right away."
"relevance.goals" = "This situation relates to my goals and plans."
"relevance.bodily motives" = "This situation relates to my physical well-being."
"relevance.social motives" = "This situation involves people who matter to me."
"relevance.identity motives" = "This situation concerns who I am and what I stand for."
"certainty.construal" = "It is clear to me what is going on in this situation."
"certainty.outlook" = "I know what will come next in this situation."
"certainty.predictability" = "I saw this situation coming."
"certainty.novelty" = "This is a new kind of situation for me."
"congruence.general" = "This is a good situation."
"congruence.outlook" = "This situation will get better with time."
"congruence.positive prediction error" = "This situation is better than I expected."
"congruence.negative prediction error" = "This situation is worse than I expected."
"control.general" = "This situation is under my control."
"control.select" = "I can decide whether to stay in this situation or leave it."
"control.vicarious" = "Someone can handle this situation for me."
"control.effortful" = "I have to exert effort in this situation."
"accountability.self" = "I am responsible for this situation."
"accountability.other" = "Someone else is responsible for this situation."
"accountability.intentionality" = "This situation was caused intentionally."
"accountability.fairness" = "This situation is fair and deserved."

[templates.appraisals]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. Please indicate how much the given statement reflects how you feel about the event. When answering, please think back to the moment when the events described in the story had just ended.
My Situation: {scenario}
Statement: {statement}
Options:
- Strongly disagree
- Somewhat disagree
- Neither agree nor disagree
- Somewhat agree
- Strongly agree
Constraint: Respond only with one of the above labels. Do not provide any introductory text, explanation, or punctuation.
My Answer:"""

[templates.positive-level]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. You have just finished experiencing these events. Answer the following reflection based on how you truly feel in that moment.
My Situation: {scenario}
Question: How positive did this situation make you feel?
Options:
- Not at all positive
- Very slightly positive
- Slightly positive
- Moderately positive
- Quite a bit positive
- Very positive
- Extremely positive
Constraint: Respond only with one of the above labels. Do not provide any introductory text, explanation, or punctuation.
My Answer:"""

[templates.negative-level]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. You have just finished experiencing these events. Answer the following reflection based on how you truly feel in that moment.
My Situation: {scenario}
Question: How negative did this situation make you feel?
Options:
- Not at all negative
- Very slightly negative
- Slightly negative
- Moderately negative
- Quite a bit negative
- Very negative
- Extremely negative
Constraint: Respond only with one of the above labels. Do not provide any introductory text, explanation, or punctuation.
My Answer:"""

[templates.positive-labels]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. You have just finished experiencing these events. Answer the following reflection based on how you truly feel in that moment.
My Situation: {scenario}
Question: Which of the following emotion groups did you experience in this situation?
Options:
- Hopeful, optimistic, encouraged
- Grateful, appreciative, thankful
- Glad, happy, joyful
- Love, closeness, trust
- Amused, entertained
- Sympathy, concern, compassion
- Inspiration, admiration, appreciation
- Calm, peaceful, relaxed
- Proud, confident, determined
- Excited, enthusiastic, elated
Constraint:
1. If you did not feel any positive emotions, respond only with "None".
2. If you experienced any of the above, list all applicable groups exactly as they are written, separated by a semicolon (;).
3. Do not provide any introductory text, explanation, or punctuation outside of the list.
My Answer:"""

[templates.negative-labels]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. You have just finished experiencing these events. Answer the following reflection based on how you truly feel in that moment.
My Situation: {scenario}
Question: Which of the following emotion groups did you experience in this situation?
Options:
- Angry, frustrated, annoyed
- Worried, nervous, fearful
- Sad, downhearted, unhappy
- Disgust, distaste, revulsion
- Despair, hopelessness, sorrow
- Ashamed, humiliated, embarrassed
- Lonely, isolated, disconnected from others
- Panicked, alarmed, freaked out
- Guilty, blameworthy, repentant
- Confused, disoriented, surprised
Constraint:
1. If you did not feel any negative emotions, respond only with "None".
2. If you experienced any of the above, list all applicable groups exactly as they are written, separated by a semicolon (;).
3. Do not provide any introductory text, explanation, or punctuation outside of the list.
My Answer:"""

[label_maps.appraisals]
"Strongly disagree" = 1
"Somewhat disagree" = 2
"Neither agree nor disagree" = 3
"Somewhat agree" = 4
"Strongly agree" = 5

[label_maps.positive-level]
"Not at all positive" = 0
"Very slightly positive" = 1
"Slightly positive" = 2
"Moderately positive" = 3
"Quite a bit positive" = 4
"Very positive" = 5
"Extremely positive" = 6

[label_maps.negative-level]
"Not at all negative" = 0
"Very slightly negative" = 1
"Slightly negative" = 2
"Moderately negative" = 3
"Quite a bit negative" = 4
"Very negative" = 5
"Extremely negative" = 6

[label_options.negative-labels]
values = [
	"Angry, frustrated, annoyed",
	"Worried, nervous, fearful",
	"Sad, downhearted, unhappy",
	"Disgust, distaste, revulsion",
	"Despair, hopelessness, sorrow",
	"Ashamed, humiliated, embarrassed",
	"Lonely, isolated, disconnected from others",
	"Panicked, alarmed, freaked out",
	"Guilty, blameworthy, repentant",
	"Confused, disoriented, surprised",
]

[label_options.positive-labels]
values = [
	"Hopeful, optimistic, encouraged",
	"Grateful, appreciative, thankful",
	"Glad, happy, joyful",
	"Love, closeness, trust",
	"Amused, entertained",
	"Sympathy, concern, compassion",
	"Inspiration, admiration, appreciation",
	"Calm, peaceful, relaxed",
	"Proud, confident, determined",
	"Excited, enthusiastic, elated",
]


[templates.core-appraisals]
user = """Instruction: Imagine you are the person who wrote the following story. Read it carefully and internalize the feelings and situation described. Please answer the following questions in the first person. When answering, please think back to the moment when the events described in the story had just ended. Keep your response concise and try to keep it within 60 tokens.
My Situation: {scenario}
Question: {question}
My Answer:"""

[core-appraisals.questions]
"relevance" = "When the event happened, how much did it matter to you? Why?"
"congruence" = "In what ways did this situation help or hurt you?"
"accountability" = "Who or what did you feel was most responsible for all of this?"
"control" = "Did you feel like you were in control? Why?"
"certainty" = "Did things go as you expected? If not, what was unexpected?"

